/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsp.dsi.janela;

import ifsp.dsi.bo.BebidaBO;
import ifsp.dsi.bo.FuncionarioBO;
import ifsp.dsi.bo.MontavelBO;
import ifsp.dsi.entidade.Funcionario;
import ifsp.dsi.entidade.Ingrediente;
import ifsp.dsi.entidade.Mesa;
import ifsp.dsi.entidade.Montavel;
import ifsp.dsi.entidade.MontavelIngrediente;
import ifsp.dsi.entidade.MontavelIngredientes;
import ifsp.dsi.entidade.ProdutoBase;
import ifsp.dsi.enums.MontavelTipo;
import java.util.List;

/**
 *
 * @author repolho
 */
public class JanelaConsumo extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConsumo
     */
    public JanelaConsumo(Funcionario funcionario, Mesa mesa) {
        initComponents();
        
        populaCombos();
        
        cboFuncionarios.setSelectedItem(funcionario);
        
        lblTitulo.setText("Consumo Mesa " + String.valueOf(mesa.getNumero()));                
        
        txtSafra.setEnabled(false);
        txtTipoUva.setEnabled(false);
        txtIngredientes.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboPratos = new javax.swing.JComboBox<>();
        cboBebidas = new javax.swing.JComboBox<>();
        cboDrinks = new javax.swing.JComboBox<>();
        cboVinhos = new javax.swing.JComboBox<>();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIngredientes = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSafra = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtSafra = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lblTipoUva = new javax.swing.JLabel();
        txtTipoUva = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtQtdePessoas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cboFuncionarios = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cboSucos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Consumo Mesa X");
        lblTitulo.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1152, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel2.setText("Pratos");

        jLabel4.setText("Drinks");

        jLabel5.setText("Vinhos");

        jLabel3.setText("Bebidas");

        cboPratos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPratosItemStateChanged(evt);
            }
        });

        cboBebidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBebidasItemStateChanged(evt);
            }
        });

        cboDrinks.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDrinksItemStateChanged(evt);
            }
        });

        cboVinhos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboVinhosItemStateChanged(evt);
            }
        });

        txtNomeProduto.setEditable(false);
        txtNomeProduto.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtNomeProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomeProduto.setText("Nome do Produto");
        txtNomeProduto.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setText("Ingredientes");

        txtIngredientes.setEditable(false);
        txtIngredientes.setColumns(20);
        txtIngredientes.setRows(5);
        jScrollPane1.setViewportView(txtIngredientes);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Quantidade");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Valor");

        lblSafra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSafra.setText("Safra");

        txtQtde.setEditable(false);
        txtQtde.setText("0");

        txtValor.setEditable(false);

        txtSafra.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PratoX",  new Integer(6),  new Double(20.0),  new Double(120.0), null},
                {"Água",  new Integer(5),  new Double(2.0),  new Double(10.0), null},
                {"Suco ",  new Integer(1),  new Double(6.5),  new Double(6.5), null},
                {"Vinho",  new Integer(1),  new Double(100.0),  new Double(100.0), null},
                {"Caipirinha",  new Integer(2),  new Double(14.5),  new Double(29.0), null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor", "Sub Total", "#"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Consumo");

        lblTipoUva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoUva.setText("Tipo Uva");

        txtTipoUva.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setText("Quantidade de Pessoas");

        txtQtdePessoas.setText("0");

        jButton1.setText("Remover selecionado(s)");

        jButton2.setText("Adicionar");

        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton3.setText("Finalizar Mesa");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setText("Funcionário");

        jLabel14.setText("Sucos");

        cboSucos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSucosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPratos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSucos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboVinhos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSafra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTipoUva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQtde)
                                    .addComponent(txtValor)
                                    .addComponent(txtSafra)
                                    .addComponent(txtTipoUva))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(cboFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQtdePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 903, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtQtdePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(cboFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSafra)
                                    .addComponent(txtSafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTipoUva)
                                    .addComponent(txtTipoUva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cboPratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cboBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(cboSucos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cboDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cboVinhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPratosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPratosItemStateChanged
        MontavelBO bo = new MontavelBO();
        
        Montavel montavel = (Montavel) cboPratos.getSelectedItem();
        
        MontavelIngredientes ingredientes = bo.listarByMontavel(montavel);
        
        List<MontavelIngrediente> list = ingredientes.getMontavelIngredientes();
        
        StringBuilder builder = new StringBuilder();
        
        for (MontavelIngrediente montavelIngrediente : list) {
            Ingrediente i = montavelIngrediente.getIngrediente();
            builder.append(i.getNome() + ", ");
        }
        
        txtNomeProduto.setText(montavel.getNome());
        txtValor.setText(String.valueOf(montavel.getValorVenda()));
        txtIngredientes.setText(builder.toString());
        
        txtSafra.setVisible(false);
        lblSafra.setVisible(false);
        txtTipoUva.setVisible(false);
        lblTipoUva.setVisible(false);
    }//GEN-LAST:event_cboPratosItemStateChanged

    private void cboBebidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBebidasItemStateChanged
        
        txtSafra.setVisible(false);
        lblSafra.setVisible(false);
        txtTipoUva.setVisible(false);
        lblTipoUva.setVisible(false);
    }//GEN-LAST:event_cboBebidasItemStateChanged

    private void cboSucosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSucosItemStateChanged
        MontavelBO bo = new MontavelBO();
        
        Montavel montavel = (Montavel) cboSucos.getSelectedItem();
        
        MontavelIngredientes ingredientes = bo.listarByMontavel(montavel);
        
        List<MontavelIngrediente> list = ingredientes.getMontavelIngredientes();
        
        StringBuilder builder = new StringBuilder();
        
        for (MontavelIngrediente montavelIngrediente : list) {
            Ingrediente i = montavelIngrediente.getIngrediente();
            builder.append(i.getNome() + ", ");
        }
        
        txtNomeProduto.setText(montavel.getNome());
        txtValor.setText(String.valueOf(montavel.getValorVenda()));
        txtIngredientes.setText(builder.toString());
        
        txtSafra.setVisible(false);
        lblSafra.setVisible(false);
        txtTipoUva.setVisible(false);
        lblTipoUva.setVisible(false);
    }//GEN-LAST:event_cboSucosItemStateChanged

    private void cboDrinksItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDrinksItemStateChanged
        MontavelBO bo = new MontavelBO();
        
        Montavel montavel = (Montavel) cboDrinks.getSelectedItem();
        
        MontavelIngredientes ingredientes = bo.listarByMontavel(montavel);
        
        List<MontavelIngrediente> list = ingredientes.getMontavelIngredientes();
        
        StringBuilder builder = new StringBuilder();
        
        for (MontavelIngrediente montavelIngrediente : list) {
            Ingrediente i = montavelIngrediente.getIngrediente();
            builder.append(i.getNome() + ", ");
        }
        
        txtNomeProduto.setText(montavel.getNome());
        txtValor.setText(String.valueOf(montavel.getValorVenda()));
        txtIngredientes.setText(builder.toString());
        
        txtSafra.setVisible(false);
        lblSafra.setVisible(false);
        txtTipoUva.setVisible(false);
        lblTipoUva.setVisible(false);
    }//GEN-LAST:event_cboDrinksItemStateChanged

    private void cboVinhosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboVinhosItemStateChanged
        txtSafra.setVisible(true);
        lblSafra.setVisible(true);
        txtTipoUva.setVisible(true);
        lblTipoUva.setVisible(true);
    }//GEN-LAST:event_cboVinhosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ProdutoBase> cboBebidas;
    private javax.swing.JComboBox<ProdutoBase> cboDrinks;
    private javax.swing.JComboBox<Funcionario> cboFuncionarios;
    private javax.swing.JComboBox<ProdutoBase> cboPratos;
    private javax.swing.JComboBox<ProdutoBase> cboSucos;
    private javax.swing.JComboBox<ProdutoBase> cboVinhos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSafra;
    private javax.swing.JLabel lblTipoUva;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtIngredientes;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtQtde;
    private javax.swing.JTextField txtQtdePessoas;
    private javax.swing.JTextField txtSafra;
    private javax.swing.JTextField txtTipoUva;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void populaCombos() {
        MontavelBO montavelBO = new MontavelBO();
        BebidaBO bebidaBO = new BebidaBO();
        FuncionarioBO funcionarioBO = new FuncionarioBO();
        
        cboBebidas.removeAllItems();
        
        cboVinhos.removeAllItems();
        
        List<Montavel> montavel = montavelBO.listarByTipo(MontavelTipo.SUCO);
        cboSucos.removeAllItems();
        for (Montavel m : montavel) {
            cboSucos.addItem(m);
        }
        
        montavel = montavelBO.listarByTipo(MontavelTipo.DRINK);
        cboDrinks.removeAllItems();
        for (Montavel m : montavel) {
            cboDrinks.addItem(m);
        }
        
        montavel = montavelBO.listarByTipo(MontavelTipo.PRATO);
        cboPratos.removeAllItems();
        for (Montavel m : montavel) {
            cboPratos.addItem(m);
        }
        
        cboFuncionarios.removeAllItems();
        List<Funcionario> funcionarios = funcionarioBO.listarTodos();
        
        for (Funcionario f : funcionarios) {
            cboFuncionarios.addItem(f);
        }
        
        
    }
}
