/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsp.dsi.janela;

import ifsp.dsi.bo.ClienteBO;
import ifsp.dsi.bo.IngredienteBO;
import ifsp.dsi.bo.MesaBO;
import ifsp.dsi.bo.ReservaBO;
import ifsp.dsi.entidade.Cliente;
import ifsp.dsi.entidade.Funcionario;
import ifsp.dsi.entidade.Ingrediente;
import ifsp.dsi.entidade.Mesa;
import ifsp.dsi.entidade.Reserva;
import ifsp.dsi.enums.MontavelTipo;
import ifsp.dsi.enums.StatusReserva;
import ifsp.dsi.janela.tabela.ModeloTabelaListaEspera;
import ifsp.dsi.janela.tabela.ModeloTabelaMesaPrincipal;
import ifsp.dsi.janela.tabela.ModeloTabelaReserva;
import ifsp.dsi.janela.util.MessageBox;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author repolho
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Variáveis ProjetoRestaurante
     */
    
    private Funcionario mFuncionario;
    private ModeloTabelaMesaPrincipal modelMesas;
    private ModeloTabelaReserva modelReservas;
    private ModeloTabelaListaEspera modelListaEspera;
    
    //Cliente retornado na busca para reserva
    private Cliente mCliente;
    
    /**
     * Creates new form JanelaPrincipal
     * @param funcionario
     */
    public JanelaPrincipal(Funcionario funcionario) {
        initComponents();
        mFuncionario = funcionario;
        
        lblNomeUsuario.setText(mFuncionario.getNome());
        
        popularTabelaMesas();
        
        popularTabelaReservas();
        
        popularTabelaListaEspera();
        
        popularCombosMesas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboCardapio = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnCardapioAtivar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnIniciarConsumo = new javax.swing.JButton();
        btnFinalizarConsumo = new javax.swing.JButton();
        cboMesas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtReservaTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAddClienteReserva = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtReservaData = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cboReservaMesa = new javax.swing.JComboBox<>();
        txtReservaNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRemoverSelcionadosReserva = new javax.swing.JButton();
        btnRemoverSelecionadosLista = new javax.swing.JButton();
        btnReservaIniciarConsumo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaReservas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaListaEspera = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mMesa = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Início");
        jLabel1.setToolTipText("");

        cboCardapio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Nenhum Cardápio Ativo--", "Cardápio 1", "Cardápio 2", "Cardápio 3" }));

        jLabel10.setText("Cardápio de hoje");

        btnCardapioAtivar.setText("Ativar");
        btnCardapioAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardapioAtivarActionPerformed(evt);
            }
        });

        jLabel13.setText("logado como:");

        lblNomeUsuario.setText("CErepolho");

        btnAtualizar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(12, 24, 248));
        btnAtualizar.setText("Atualizar janela");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCardapioAtivar)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10)
                .addComponent(btnCardapioAtivar)
                .addComponent(jLabel13)
                .addComponent(lblNomeUsuario)
                .addComponent(btnAtualizar))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Atendimento");

        btnIniciarConsumo.setText("Consumo");
        btnIniciarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarConsumoActionPerformed(evt);
            }
        });

        btnFinalizarConsumo.setText("Finalizar");

        jLabel3.setText("Mesa:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIniciarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnFinalizarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cboMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reservas / Lista de espera");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel6.setText("Telefone:");

        btnAddClienteReserva.setText("Adicionar");
        btnAddClienteReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionAddReserva(evt);
            }
        });

        jLabel11.setText("Data:");

        jLabel12.setText("Mesa:");

        jLabel5.setText("Nome:");

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBuscarCliente(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtReservaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCliente))
                    .addComponent(txtReservaData))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReservaNome))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cboReservaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddClienteReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtReservaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCliente))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtReservaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(cboReservaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtReservaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddClienteReserva)))
        );

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Reservas");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Lista de espera");

        btnRemoverSelcionadosReserva.setText("Remover selecionado(s)");
        btnRemoverSelcionadosReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionReservaRemoverSelcionados(evt);
            }
        });

        btnRemoverSelecionadosLista.setText("Remover selecionado(s)");
        btnRemoverSelecionadosLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionListaRemoverSelcionados(evt);
            }
        });

        btnReservaIniciarConsumo.setText("Iniciar consumo");
        btnReservaIniciarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionReservaIniciarConsumo(evt);
            }
        });

        modelReservas = new ModeloTabelaReserva();
        tabelaReservas.setModel(modelReservas);
        jScrollPane1.setViewportView(tabelaReservas);

        modelListaEspera = new ModeloTabelaListaEspera();
        tabelaListaEspera.setModel(modelListaEspera);
        jScrollPane2.setViewportView(tabelaListaEspera);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnReservaIniciarConsumo)
                                .addGap(164, 164, 164)
                                .addComponent(btnRemoverSelcionadosReserva))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoverSelecionadosLista, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoverSelcionadosReserva)
                    .addComponent(btnReservaIniciarConsumo)
                    .addComponent(btnRemoverSelecionadosLista))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Status das mesas");

        modelMesas = new ModeloTabelaMesaPrincipal();
        jTable1.setModel(modelMesas);
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastros");

        jMenuItem8.setText("Bebida simples");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBebida(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem10.setText("Cardapio");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCardapio(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem6.setText("Drink");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDrink(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem4.setText("Funcionario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionario(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setText("Ingrediente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngrediente(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mMesa.setText("Mesa");
        mMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMesa(evt);
            }
        });
        jMenu1.add(mMesa);

        jMenuItem5.setText("Prato");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrato(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setText("Suco");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSuco(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem11.setText("Tipo de Pagamento");
        jMenu1.add(jMenuItem11);

        jMenuItem7.setText("Vinhos");
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator1);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIngrediente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngrediente
        JanelaManterIngrediente janela = new JanelaManterIngrediente();
        janela.setVisible(true);
    }//GEN-LAST:event_menuIngrediente

    private void btnIniciarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarConsumoActionPerformed
        Mesa m = (Mesa) cboMesas.getSelectedItem();
        
        iniciarConsumo(m);
    }//GEN-LAST:event_btnIniciarConsumoActionPerformed

    private void actionListaRemoverSelcionados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionListaRemoverSelcionados
        ReservaBO bo = new ReservaBO();
        
        List<Reserva> selecionados = modelListaEspera.getSelecionados();
        
        for (Reserva item : selecionados) {
            item.setStatus(StatusReserva.CANCELADA);
            bo.salvar(item);
            
            modelListaEspera.removeRow(item);
        }
    }//GEN-LAST:event_actionListaRemoverSelcionados

    private void btnCardapioAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardapioAtivarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCardapioAtivarActionPerformed

    private void menuMesa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMesa
        JanelaManterMesa janela = new JanelaManterMesa();
        janela.setVisible(true);
    }//GEN-LAST:event_menuMesa

    private void menuFuncionario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionario
        JanelaManterFuncionario janela = new JanelaManterFuncionario();
        janela.setVisible(true);
    }//GEN-LAST:event_menuFuncionario

    private void menuPrato(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrato
        JanelaManterPrato janela = new JanelaManterPrato();
        janela.setVisible(true);
    }//GEN-LAST:event_menuPrato

    private void menuDrink(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDrink
        JanelaManterDrink janela = new JanelaManterDrink();
        janela.setVisible(true);
    }//GEN-LAST:event_menuDrink

    private void menuSuco(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSuco
        JanelaManterSuco janela = new JanelaManterSuco();
        janela.setVisible(true);
    }//GEN-LAST:event_menuSuco

    private void actionBuscarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionBuscarCliente
        
        if(txtReservaTelefone.getText().equals("")){
            MessageBox.showWarning("Telefone inválido !");
            return;
        }
        
        ClienteBO bo = new ClienteBO();
        
        mCliente = bo.getByTelefone(Long.valueOf(txtReservaTelefone.getText()));
        
        if(mCliente != null){
            txtReservaNome.setText(mCliente.getNome());
            txtReservaNome.setEnabled(false);
            
            txtReservaData.requestFocus();
            
            MessageBox.showInfo("Cliente encontrado !");
        }else{
            MessageBox.showInfo("Cliente não encontrado... Preencha os dados para finalizar !");
            
            txtReservaNome.requestFocus();
            txtReservaNome.setText("");
            txtReservaNome.setEnabled(true);            
        }
    }//GEN-LAST:event_actionBuscarCliente

    private void actionReservaIniciarConsumo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionReservaIniciarConsumo
        
        if(modelReservas.getSelecionados().isEmpty()){
            MessageBox.showWarning("Não é possível iniciar o consumo ! Selecione uma reserva para continuar.");
        }
        
        if(modelReservas.getSelecionados().size() > 1){
            MessageBox.showWarning("Não é possível iniciar o consumo com mais de uma reserva selecionada ! Verifique.");
        }
        
        Reserva reserva = modelReservas.getSelecionados().get(0);
        Mesa m = reserva.getMesa();
        
        modelReservas.removeRow(reserva);
        
        reserva.setStatus(StatusReserva.FINALIZADA);
        
        ReservaBO bo = new ReservaBO();
        bo.salvar(reserva);
        
        iniciarConsumo(m);
    }//GEN-LAST:event_actionReservaIniciarConsumo

    private void actionReservaRemoverSelcionados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionReservaRemoverSelcionados
        ReservaBO bo = new ReservaBO();
        
        List<Reserva> selecionados = modelReservas.getSelecionados();
        
        for (Reserva item : selecionados) {
            item.setStatus(StatusReserva.ESPERA);
            bo.salvar(item);
            
            modelReservas.removeRow(item);
            
            item.setSelecionado(false);
            modelListaEspera.addRow(item);
        }
        
    }//GEN-LAST:event_actionReservaRemoverSelcionados

    private void actionAddReserva(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionAddReserva
        
        if(txtReservaTelefone.getText().equals("")){
            MessageBox.showWarning("Telefone inválido !");
            return;
        }
        
        Mesa m = (Mesa) cboReservaMesa.getSelectedItem();
        
        if(mCliente == null) {
            mCliente = new Cliente(
                    txtReservaNome.getText(), 
                    Long.valueOf(txtReservaTelefone.getText())
            );
        }
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        
        Calendar data = Calendar.getInstance();
        ReservaBO bo = new ReservaBO();
        
        try {
            
            data.setTime(dateFormat.parse(txtReservaData.getText()));
            
            Reserva r = new Reserva(m, mCliente, data, StatusReserva.ESPERA);
            
            bo.salvar(r);
            
            modelReservas.addRow(r);
            
        } catch (ParseException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_actionAddReserva

    private void menuBebida(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBebida
        JanelaBebidas janela = new JanelaBebidas();
        janela.setVisible(true);
    }//GEN-LAST:event_menuBebida

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        popularTabelaReservas();
        
        popularTabelaListaEspera();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void menuCardapio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCardapio
        JanelaManterCardapio janela = new JanelaManterCardapio();
        janela.setVisible(true);
    }//GEN-LAST:event_menuCardapio

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClienteReserva;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCardapioAtivar;
    private javax.swing.JButton btnFinalizarConsumo;
    private javax.swing.JButton btnIniciarConsumo;
    private javax.swing.JButton btnRemoverSelcionadosReserva;
    private javax.swing.JButton btnRemoverSelecionadosLista;
    private javax.swing.JButton btnReservaIniciarConsumo;
    private javax.swing.JComboBox<String> cboCardapio;
    private javax.swing.JComboBox<Mesa> cboMesas;
    private javax.swing.JComboBox<Mesa> cboReservaMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JMenuItem mMesa;
    private javax.swing.JTable tabelaListaEspera;
    private javax.swing.JTable tabelaReservas;
    private javax.swing.JTextField txtReservaData;
    private javax.swing.JTextField txtReservaNome;
    private javax.swing.JTextField txtReservaTelefone;
    // End of variables declaration//GEN-END:variables

    private void popularTabelaMesas() {
        MesaBO bo = new MesaBO();
        
        modelMesas.removeAllRows();
        
        List<Mesa> lista = bo.listarTodos();
        
        for (Mesa i : lista) {
            modelMesas.addRow(i);
        }
    }

    private void popularCombosMesas() {
        MesaBO bo = new MesaBO();
        
        cboMesas.removeAllItems();
        cboReservaMesa.removeAllItems();
        
        List<Mesa> lista = bo.listarTodos();
        
        for (Mesa i : lista) {
            cboMesas.addItem(i);
            cboReservaMesa.addItem(i);
        }
    }

    private void popularTabelaReservas() {
        ReservaBO bo = new ReservaBO();
                     
        modelReservas.removeAllRows();
        
        List<Reserva> reservas = bo.listarTodos(StatusReserva.RESERVADA);
        
        for (Reserva reserva : reservas) {
            modelReservas.addRow(reserva);
        }
        
    }

    private void popularTabelaListaEspera() {
        ReservaBO bo = new ReservaBO();
                        
        modelListaEspera.removeAllRows();
        
        List<Reserva> reservas = bo.listarTodos(StatusReserva.ESPERA);
        
        for (Reserva reserva : reservas) {
            modelListaEspera.addRow(reserva);
        }
    }

    private void iniciarConsumo(Mesa m) {
        JanelaConsumo janela = new JanelaConsumo(mFuncionario,m);
        janela.setVisible(true);
    }
}
