/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifsp.dsi.janela;


import ifsp.dsi.janela.tabela.ModeloTabelaIngrediente;
import ifsp.dsi.bo.IngredienteBO;
import ifsp.dsi.entidade.Ingrediente;
import ifsp.dsi.janela.util.MessageBox;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author repolho
 */
public class JanelaManterIngrediente extends javax.swing.JFrame {

    
    private IngredienteBO mIngredienteBO;
    private Ingrediente mIngrediente;
    private ModeloTabelaIngrediente model;
    
    /**
     * Creates new form JanelaCadItemProduto
     */
    public JanelaManterIngrediente() {
        initComponents();
        
        mIngredienteBO = new IngredienteBO();
        
        popularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtQtdeEstoque = new javax.swing.JTextField();
        txtQtdeMinima = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtValorCusto = new javax.swing.JTextField();
        flagPrato = new javax.swing.JCheckBox();
        flagBabida = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnExcluirSelecionados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel2.setText("Id");

        jLabel3.setText("Nome");

        txtId.setEditable(false);
        txtId.setToolTipText("Id gerado automaticamente");

        txtNome.setToolTipText("Nome do ingrediente");

        txtQtdeEstoque.setToolTipText("Quantidade atual no estoque");

        txtQtdeMinima.setToolTipText("Quantidade mínima para manter em estoque");

        jLabel4.setText("Estoque");

        jLabel5.setText("Qtde Mínima");

        jLabel6.setText("Valor de Custo");

        txtValorCusto.setToolTipText("Valor de custo");

        flagPrato.setText("Vai no Prato ?");
        flagPrato.setToolTipText("Informar se o ingrediente vai em algum prato");
        flagPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagPratoActionPerformed(evt);
            }
        });

        flagBabida.setText("Vai na Bebida ?");
        flagBabida.setToolTipText("Informar se o ingrediente vai em alguma bebida ou drink");
        flagBabida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagBabidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciamento dos Ingredientes");
        jLabel1.setToolTipText("");

        btnExcluirSelecionados.setText("Excluir selecionado(s)");
        btnExcluirSelecionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirSelecionados(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionNovo(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionEditar(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionExcluir(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionSalvar(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionaCancelar(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditar)
                        .addComponent(btnNovo)
                        .addComponent(btnCancelar)
                        .addComponent(btnExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        model = new ModeloTabelaIngrediente();
        table.setModel(model);
        table.setColumnSelectionAllowed(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtQtdeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flagPrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flagBabida)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirSelecionados))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtdeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQtdeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flagPrato)
                            .addComponent(flagBabida))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirSelecionados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flagPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagPratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flagPratoActionPerformed

    private void flagBabidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagBabidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flagBabidaActionPerformed

    private void actionSalvar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionSalvar
        
        if(!validaForm())
            return;
        
        mIngrediente = new Ingrediente(
                Long.valueOf(txtId.getText()),
                txtNome.getText(),
                new BigDecimal(txtValorCusto.getText()),
                Double.valueOf(txtQtdeEstoque.getText()),
                Double.valueOf(txtQtdeMinima.getText()),
                flagPrato.isSelected(),
                flagBabida.isSelected()
        );
        
        mIngredienteBO.salvar(mIngrediente);
        model.addRow(mIngrediente);
        MessageBox.showInfo("Salvo com sucesso !");
        
    }//GEN-LAST:event_actionSalvar

    private void actionNovo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionNovo
        preparaNovo();
    }//GEN-LAST:event_actionNovo

    private void actionEditar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionEditar
        preparaEditar();
    }//GEN-LAST:event_actionEditar

    private void actionExcluir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionExcluir
        if(MessageBox.showAskYesNo("Excluir ?") == MessageBox.YES_OPTION){
            mIngredienteBO.apagar(mIngrediente);                    
            model.removeRow(mIngrediente);
        }        
                        
    }//GEN-LAST:event_actionExcluir

    private void btnExcluirSelecionados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirSelecionados
        List<Ingrediente> selecionados = model.getSelecionados();
        
        if(MessageBox.showAskYesNo("Excluir ?") == MessageBox.YES_OPTION){
            for (Ingrediente i : selecionados) {

                if(mIngredienteBO.apagar(i))
                    model.removeRow(i);
            }
        }
        
        
    }//GEN-LAST:event_btnExcluirSelecionados

    private void actionaCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionaCancelar
        if(mIngrediente != null)
            atualizaValores();
        
        preparaEditavel(false);
    }//GEN-LAST:event_actionaCancelar

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        mIngrediente = model.getValueAt(table.getSelectedRow());
        atualizaValores();
        preparaEditavel(false);
    }//GEN-LAST:event_tableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirSelecionados;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox flagBabida;
    private javax.swing.JCheckBox flagPrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtdeEstoque;
    private javax.swing.JTextField txtQtdeMinima;
    private javax.swing.JTextField txtValorCusto;
    // End of variables declaration//GEN-END:variables

    private void preparaNovo() {
        
        preparaEditavel(true);
        
        txtId.setText("0");
        txtNome.setText("");
        txtQtdeEstoque.setText("");
        txtQtdeMinima.setText("");
        txtValorCusto.setText("");
        flagBabida.setSelected(false);
        flagPrato.setSelected(false);
        
        txtNome.requestFocus();
        
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }

    private void preparaEditavel(boolean editavel){
        
        txtId.setEnabled(false);
        
        txtNome.setEnabled(editavel);
        txtQtdeEstoque.setEnabled(editavel);
        txtQtdeMinima.setEnabled(editavel);
        txtValorCusto.setEnabled(editavel);
        flagBabida.setEnabled(editavel);
        flagPrato.setEnabled(editavel);
    }
    
    private void preparaEditar() {
        preparaEditavel(true);
        
        txtNome.requestFocus();
        
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnNovo.setEnabled(false);
    }

    private boolean validaForm() {
        boolean valid = true;
        String texto = "";
        
        if(txtNome.getText().equals("")){
            texto = "Nome não pode estar vazio !";
            valid = false;
        }
        
        if(txtQtdeEstoque.getText().equals("")){
            txtQtdeEstoque.setText("0");
        }else if(Double.valueOf(txtQtdeEstoque.getText()) < 0){
            String aux = "Quantidade de estoque deve ser um valor positivo ou zero !";
            texto += texto.equals("") ? aux : "\n" + aux;
            valid = false;
        }
        
        if(txtQtdeMinima.getText().equals("")){
            txtQtdeMinima.setText("0");
        }else if(Double.valueOf(txtQtdeMinima.getText()) < 0){
            String aux = "Quantidade mínima de estoque deve ser um valor positivo ou zero !";
            texto += texto.equals("") ? aux : "\n" + aux;
            valid = false;
        }
        
        if(txtValorCusto.getText().equals("") || Double.valueOf(txtValorCusto.getText()) == 0){
            String aux = "Valor de custo deve ter um valor !";
            texto += texto.equals("") ? aux : "\n" + aux;
            valid = false;
        }
        
        if(!flagBabida.isSelected() && !flagPrato.isSelected()){
            String aux = "O ingrediente deve fazer parte de pelos Prato ou Bebida !";
            texto += texto.equals("") ? aux : "\n" + aux;
            valid = false;
        }
        
        if(!valid){
            MessageBox.showWarning(texto);
        }
        
        return valid;
    }

    private void popularTabela() {
        
        List<Ingrediente> lista = mIngredienteBO.listarTodos();
        
        for (Ingrediente i : lista) {
            model.addRow(i);
        }

    }

    private void atualizaValores() {
        txtId.setText(
                String.valueOf(mIngrediente.getId())
        );
        
        txtNome.setText(
                mIngrediente.getNome()
        );
        
        txtQtdeEstoque.setText(
                String.valueOf(mIngrediente.getQtdeEstoque())
        );
        
        txtQtdeMinima.setText(
                String.valueOf(mIngrediente.getQtdeMinima())
        );
        
        txtValorCusto.setText(
                String.valueOf(mIngrediente.getValorCusto())
        );
        
        flagBabida.setSelected(
                mIngrediente.isPresentBebida()
        );
        
        flagPrato.setSelected(
                mIngrediente.isPresentPrato()
        );
    }
}
